### ISSUE TITLE
prod instance is broken

### ISSUE THREAD

**Issue by troggy** [leapdao/slack-analytics#2]
This lambda feeds leapdao.org with the number of Slack members.

Currently it throws:

![image](https://user-images.githubusercontent.com/163447/59367122-2a640000-8d44-11e9-9580-cb482858137a.png)

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
at fetch.then.then.data (/var/task/handler.js:14:28)
at <anonymous>
```

*Impact:* no Slack members shown on the websites

**Comment by art1c0** [comment]
fixed by re-deploying the lambda with a new slack token
